package com.innovx.gestionrh.Entity;

public enum InternDocumentType {
    ATTESTATION_ASSURANCE,
    CARTE_NATIONALE,
    FICHE_ANTHROPOMETRIQUE,
    COPIE_CERTIFIEE_DIPLOMES,
    RELEVE_IDENTITE_BANCAIRE,
    CV,
    CONVENTION_STAGE,
    FICHE_EVALUATION,
    CHARTE_ENGAGEMENT,
    ATTESTATION_STAGE
}
